# Generated by Django 4.2.5 on 2023-11-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
