# Generated by Django 4.2.5 on 2023-11-17 07:45

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.user_directory_path),
        ),
    ]
